name: Lock pull request when approved
on:
  pull_request_review:
    types: [submitted]
jobs:
  check-state:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: lock pull request
        uses: sudo-bot/action-pull-request-lock@v1.0.5
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ github.event.pull_request.number }}
            lock-reason: resolved